[package]

name = "voxel-data"
version = "0.0.0"
authors = [
  "Zeke Foppa <benjamin.foppa@gmail.com>",
]

[lib]
name = "voxel_data"
path = "./src/mod.rs"

[dependencies]
cgmath = "0.10.*"
clippy = "*"
collision = "*"
log = "*"
rustc-serialize = "*"
